import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  compileMappingDocumentToRecords,
  type ProviderLocationMappingDocument,
  type ProviderLocationMappingNode,
  type ProviderLocationRecord,
} from "@ongkirhub/core";
import { parse as parseYaml } from "yaml";

export class LocationCompileError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "LocationCompileError";
  }
}

function assertNonEmptyString(
  value: unknown,
  label: string,
): asserts value is string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new LocationCompileError(`${label} is required`);
  }
}

function validateNode(
  node: unknown,
  path: string,
  seenProviderIds: Set<string>,
): ProviderLocationMappingNode {
  if (node === null || typeof node !== "object") {
    throw new LocationCompileError(`${path} must be an object`);
  }

  const raw = node as Record<string, unknown>;
  assertNonEmptyString(raw.providerId, `${path}.providerId`);
  assertNonEmptyString(raw.name, `${path}.name`);

  if (seenProviderIds.has(raw.providerId)) {
    throw new LocationCompileError(
      `Duplicate providerId "${raw.providerId}" at ${path}`,
    );
  }
  seenProviderIds.add(raw.providerId);

  const validated: ProviderLocationMappingNode = {
    providerId: raw.providerId.trim(),
    name: raw.name.trim(),
  };

  if (raw.aliases !== undefined) {
    if (!Array.isArray(raw.aliases)) {
      throw new LocationCompileError(`${path}.aliases must be an array`);
    }
    validated.aliases = raw.aliases.map((alias, index) => {
      assertNonEmptyString(alias, `${path}.aliases[${index}]`);
      return (alias as string).trim();
    });
  }

  if (raw.postalCodes !== undefined) {
    if (!Array.isArray(raw.postalCodes)) {
      throw new LocationCompileError(`${path}.postalCodes must be an array`);
    }
    validated.postalCodes = raw.postalCodes.map((code, index) => {
      assertNonEmptyString(code, `${path}.postalCodes[${index}]`);
      return (code as string).trim();
    });
  }

  if (raw.children !== undefined) {
    if (!Array.isArray(raw.children) || raw.children.length === 0) {
      throw new LocationCompileError(
        `${path}.children must be a non-empty array when present`,
      );
    }
    validated.children = raw.children.map((child, index) =>
      validateNode(child, `${path}.children[${index}]`, seenProviderIds),
    );
  }

  return validated;
}

export function parseMappingDocument(
  source: unknown,
): ProviderLocationMappingDocument {
  if (source === null || typeof source !== "object") {
    throw new LocationCompileError("YAML root must be an object");
  }

  const raw = source as Record<string, unknown>;
  assertNonEmptyString(raw.provider, "provider");
  assertNonEmptyString(raw.version, "version");

  if (!Array.isArray(raw.countries) || raw.countries.length === 0) {
    throw new LocationCompileError("countries must be a non-empty array");
  }

  const seenProviderIds = new Set<string>();
  const countries = raw.countries.map((country, countryIndex) => {
    if (country === null || typeof country !== "object") {
      throw new LocationCompileError(
        `countries[${countryIndex}] must be an object`,
      );
    }
    const countryRaw = country as Record<string, unknown>;
    assertNonEmptyString(
      countryRaw.countryCode,
      `countries[${countryIndex}].countryCode`,
    );
    if (
      !Array.isArray(countryRaw.nodes) ||
      countryRaw.nodes.length === 0
    ) {
      throw new LocationCompileError(
        `countries[${countryIndex}].nodes must be a non-empty array`,
      );
    }

    return {
      countryCode: (countryRaw.countryCode as string).trim(),
      nodes: countryRaw.nodes.map((node, nodeIndex) =>
        validateNode(
          node,
          `countries[${countryIndex}].nodes[${nodeIndex}]`,
          seenProviderIds,
        ),
      ),
    };
  });

  return {
    provider: raw.provider.trim(),
    version: raw.version.trim(),
    countries,
  };
}

export function compileYamlSourceToRecords(
  yamlSource: string,
): ProviderLocationRecord[] {
  const parsed = parseYaml(yamlSource);
  const document = parseMappingDocument(parsed);
  if (document.provider !== "rajaongkir") {
    throw new LocationCompileError(
      `Expected provider "rajaongkir", received "${document.provider}"`,
    );
  }
  return compileMappingDocumentToRecords(document);
}

function serializeRecords(records: ProviderLocationRecord[]): string {
  return `// AUTO-GENERATED by src/location/compile.ts — do not edit manually
import type { ProviderLocationRecord } from "@ongkirhub/core";

export const RAJAONGKIR_LOCATION_RECORDS: ProviderLocationRecord[] = ${JSON.stringify(records, null, 2)};
`;
}

export function writeGeneratedRecords(
  records: ProviderLocationRecord[],
  outputPath: string,
): void {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, serializeRecords(records), "utf8");
}

const moduleDir = dirname(fileURLToPath(import.meta.url));
const defaultSourcePath = join(moduleDir, "source", "locations.yaml");
const defaultOutputPath = join(moduleDir, "generated", "locations.generated.ts");

export function compileDefaultLocationSource(): ProviderLocationRecord[] {
  const yamlSource = readFileSync(defaultSourcePath, "utf8");
  const records = compileYamlSourceToRecords(yamlSource);
  writeGeneratedRecords(records, defaultOutputPath);
  return records;
}

const isMainModule =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === process.argv[1];

if (isMainModule) {
  compileDefaultLocationSource();
}
